import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "@/app/globals.css"
import { StarBackground } from "@/components/effects/star-background"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Galaxy Smart Wallet",
  description: "Generated by Create Next App",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" type="image/png" href="/images/galaxy-smart-wallet-logo.png" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative bg-[#0A0B1E] text-white`}>
        <StarBackground />
        <main className="relative z-10">{children}</main>
      </body>
    </html>
  )
}
